### PR TITLE
Contract test for additional identifiers. 

### PR DESCRIPTION
**Pull request by prerna-p**
*Issue #, if available:*

*Description of changes:*
First we check if resource has additional identifiers, otherwise the test is skipped. Then the test compares created model with the fetched resource model.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ammokhov — CHANGES_REQUESTED** [review]
`pre-commit` failes on `flake`

**Comment by prerna-p** [comment]
> `pre-commit` failed on `flake`

@ammokhov  precommit is passing locally
isort....................................................................Passed
black....................................................................Passed
Check for case conflicts.................................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
Trim Trailing Whitespace.................................................Passed
Flake8...................................................................Passed
Pretty format JSON.......................................................Passed
Check for merge conflicts................................................Passed
Check blanket noqa.......................................................Passed
check for not-real mock methods..........................................Passed
use logger.warning(......................................................Passed
bandit...................................................................Passed
pylint-local.............................................................Passed
pytest-local.............................................................Passed

**Comment by ammokhov** [comment]
> > `pre-commit` failed on `flake`
> 
> @ammokhov precommit is passing locally
> isort....................................................................Passed
> black....................................................................Passed
> Check for case conflicts.................................................Passed
> Fix End of Files.........................................................Passed
> Mixed line ending........................................................Passed
> Trim Trailing Whitespace.................................................Passed
> Flake8...................................................................Passed
> Pretty format JSON.......................................................Passed
> Check for merge conflicts................................................Passed
> Check blanket noqa.......................................................Passed
> check for not-real mock methods..........................................Passed
> use logger.warning(......................................................Passed
> bandit...................................................................Passed
> pylint-local.............................................................Passed
> pytest-local.............................................................Passed

did you include modified files in the commit? this is what travis produced in every job
```
seed isort known_third_party.............................................Passed
isort....................................................................Passed
black....................................................................Passed
Check for case conflicts.................................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
Trim Trailing Whitespace.................................................Passed
Flake8...................................................................Failed
- hook id: flake8
- exit code: 1

src/rpdk/core/contract/suite/handler_create.py:107:40: F821 undefined name 'create_model_with_properties_in_path'
```

**Comment by prerna-p** [comment]
> > > `pre-commit` failed on `flake`
> > 
> > 
> > @ammokhov precommit is passing locally
> > isort....................................................................Passed
> > black....................................................................Passed
> > Check for case conflicts.................................................Passed
> > Fix End of Files.........................................................Passed
> > Mixed line ending........................................................Passed
> > Trim Trailing Whitespace.................................................Passed
> > Flake8...................................................................Passed
> > Pretty format JSON.......................................................Passed
> > Check for merge conflicts................................................Passed
> > Check blanket noqa.......................................................Passed
> > check for not-real mock methods..........................................Passed
> > use logger.warning(......................................................Passed
> > bandit...................................................................Passed
> > pylint-local.............................................................Passed
> > pytest-local.............................................................Passed
> 
> did you include modified files in the commit? this is what travis produced in every job
> 
> ```
> seed isort known_third_party.............................................Passed
> isort....................................................................Passed
> black....................................................................Passed
> Check for case conflicts.................................................Passed
> Fix End of Files.........................................................Passed
> Mixed line ending........................................................Passed
> Trim Trailing Whitespace.................................................Passed
> Flake8...................................................................Failed
> - hook id: flake8
> - exit code: 1
> 
> src/rpdk/core/contract/suite/handler_create.py:107:40: F821 undefined name 'create_model_with_properties_in_path'
> ```

Yes I did. The issue is this change requires a method that a [previous PR](https://github.com/aws-cloudformation/cloudformation-cli/pull/569) removed. So holding off till we are able to revert that change.

**Pull request closed without merging**
