### PR TITLE
Update readme with TypeScript plugin

### PR DESCRIPTION
**Pull request by eduardomourar**
*Issue #, if available:* N/A

*Description of changes:* Add reference for the community driven plugin for TypeScript (consequently for JavaScript).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rjlohan** [comment]
> I would rather see aws-cloudformation or awslabs adopt the repo first.

We are working on this. We will need to retrofit the V2.0 protocol changes as well.

**Comment by eduardomourar** [comment]
@rjlohan , I have started the changes for V2.0 protocol in eduardomourar/cloudformation-cli-typescript-plugin#13.

**Comment by LaikaN57** [comment]
@rjlohan bump. Looks like @eduardomourar got the v2 merged into their repo. How is the AWS version going? We should close this PR in favor of an AWS driven effort or fork @eduardomourar's repo into AWS. Thoughts?

**Comment by PatMyron** [comment]
replaced by https://github.com/aws-cloudformation/cloudformation-cli/pull/726

**Pull request closed without merging**
